# Generated by Django 5.2.12 on 2026-04-05 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grupo',
            name='biografia',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='grupo',
            name='genero',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
