# Generated by Django 5.2.12 on 2026-04-15 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('principal', '0002_alter_grupo_biografia_alter_grupo_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserva',
            name='respuesta_sala',
        ),
        migrations.AddField(
            model_name='reserva',
            name='confirmacion_sala',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
